### ISSUE TITLE
Improving the page of the getting started

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs_docs#27]
### Todo List

- [ ] Improving the page of `All in one in a local node` (Using LeoFS' package)
- [ ] Improving the page of  `Building a cluster` (Using `leofs_ansible`)
- [ ] Adding the page of how to build LeoFS environment with LeoFS' docker images

* [Getting Started on LeoFS' website](http://leo-project.net/leofs/docs/getting_started/getting_started.html)
