### ISSUE TITLE
Improving the page of LeoFS' installation

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs_docs#28]
### Todo List

- [ ] Adding the page of how to install LeoFS with LeoFS' package
- [ ] Improving the page of `installation` for CentOS 6/7 and Ubuntu 14.04/16.04
- [ ] Moving `Firewall Rules` to the page of `Configuration`

* [Installation on LeoFS' website](http://leo-project.net/leofs/docs/installation/install.html)
